/*
modified from https://github.com/amnweb/yasb-themes/tree/main/themes/d49a15b7-3ea1-4fd4-9fd4-3e8279c888a2
for use with YASB

todo: fix calendar & active window 
*/
:root {
    --microfiber: #24273a;
    --microfiberhalf: #24273a80;
    --focus: rgba(255, 255, 255, 0.116);
    --glacier: #cad3f5;
}
* {
	font-size: 12px;
	font-weight: 600;
	font-family: "JetBrainsMono NFP";
	margin: 0;
	padding: 0;
    color: #a6abcc;
}
.yasb-bar {
	padding: 0;
	margin: 0;
} 
.widget {
	background-color: var(--microfiber);
	padding: 0 4px;
	margin: 0 4px;
    border-radius: 12px;
}
.dark .widget {
	background-color: var(--glacier);
}
.widget .label {
	padding: 0px 2px; 
}
.widget .label.alt {
	padding: 0px 8px;
}
.icon {
	font-size: 16px;
}

.volume-widget .icon {
	margin: 1px 2px 0 0;
}
.audio-menu {
    background-color: var(--microfiberhalf);
    min-width: 300px;
}
.audio-menu .system-volume-container .volume-slider {
    border: none;
    
}
.audio-menu .audio-container .device {
    background-color:transparent;
    color: var(--glacier);
    border: none;
    padding:6px 8px 6px 4px;
    margin: 2px 0;
    font-size: 12px;
    border-radius: 4px;
}
.audio-menu .audio-container .device.selected {
    background-color: rgba(255, 255, 255, 0.085);
   
}
.audio-menu .audio-container .device:hover {
    background-color: rgba(255, 255, 255, 0.06);
}

.weather-widget,
.volume-widget {
    padding:0 6px;
}
.weather-widget .icon {
	font-size: 16px;
	margin: 0 2px 0px 0;
}

.taskbar-widget,
.dark .taskbar-widget {
    padding: 0;
    margin: 0;
    border: none;
    background-color: transparent;
}
.taskbar-widget .app-container{
    padding:0 6px;
    border: none;
    margin: 0;
}
.taskbar-widget .app-container .app-title {
    padding-left: 4px;
}
.label,
.icon {
	color: var(--glacier);
}
*.dark .label,
*.dark .icon {
	color: #292c3c
}

.home-widget {
    padding: 0 8px 0 8px;
	border-radius: 12px;   
}
.home-widget .widget-container {
    background-color: #ffff;
    border-radius: 8px;    
}
.home-widget .label {
	font-weight: bold;
}

.home-menu {
    background-color: var(--microfiberhalf);
}
.home-menu .menu-item {
    padding: 8px 48px 9px 16px;
    font-size: 12px;
    font-family: "JetBrainsMono NFP";
    color: var(--glacier);
    font-weight: 600;
}
.home-menu .menu-item:hover {
    background-color: var(--focus);
    color: var(--glacier);
}
.home-menu .separator {
    max-height: 1px;
    background-color: rgba(157, 180, 141, 0.116);
}

.systray {
    background: var(--microfiber);
    border: none;
    margin: 0;
}
.systray .unpinned-container {
    background: var(--microfiber);
    border-radius: 8px;
}
.systray .pinned-container {
    background: var(--microfiber);
}
.systray .pinned-container[forceshow=true] {
    background: rgb(55, 0, 255);
}
.systray .button {
    border-radius: 4px;
    padding: 2px 2px;
}
.systray .button:hover {
    background: var(--focus);
}
.systray .button[dragging=true] {
    background: var(--glacier);
    border-color: #486fff;
}
.systray .unpinned-visibility-btn {
    border-radius: 4px;
    height: 20px;
    width: 16px;
}
.systray .unpinned-visibility-btn:checked {
    background: var(--focus);
}
.systray .unpinned-visibility-btn:hover {
    border: 1px solid var(--focus);
    border-radius: 4px;
    border-color: var(--focus);
}

.wifi-widget {
    background-color: transparent;
    color: #486fff; 
    border: none;
}

.wifi-menu {
    max-height: 350px;
    min-height: 375px;
    min-width: 375px;
}

.wifi-menu .progress-bar {
    max-height: 2px;
}

.wifi-menu .progress-bar::chunk {
    background-color: #4cc2ff;
}

.wifi-menu .header {
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 2px;
    padding: 12px;
    background-color: var(--microfiberhalf);
    color: white;
    border-bottom: 1px solid var(--microfiberhalf);
}

.wifi-menu .error-message {
    
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 2px;
    padding: 12px;
    background-color: red;
    color: white;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.wifi-menu .wifi-list {
    background-color: var(--microfiberhalf);
    margin-right: 3px;
}

.wifi-menu .wifi-item {
    min-height: 35px;
    padding: 2px 12px;
    margin: 2px 4px;
}

.wifi-menu .wifi-item:hover {
    background-color: var(--focus);
    border-radius: 6px;
}

.wifi-menu .wifi-item[active=true] {
    background-color: rgba(255, 255, 255, 0.15);
    font-size: 14px;
    border-radius: 6px;
    min-height: 80px;
}

.wifi-menu .wifi-item .icon {
    font-family: 'Segoe Fluent Icons';
    font-size: 26px;
    margin-right: 10px;
}

.wifi-menu .wifi-item .name {
    font-size: 14px;
    margin-right: 10px;
}

.wifi-menu .wifi-item .password {
    background-color: transparent;
    font-size: 14px;
}

.wifi-menu .wifi-item .status {
    font-size: 14px;
}

.wifi-menu .wifi-item .strength {
    font-size: 14px;
}

.wifi-menu .wifi-item .controls-container {
    padding-top: 8px;
}

.wifi-menu .wifi-item .connect {
    background-color: rgba(255, 255, 255, 0.15);
    padding: 4px 30px;
    border-radius: 4px;
    border: none;
    font-size: 14px;
}

.wifi-menu .wifi-item .connect:hover {
    background-color: rgba(255, 255, 255, 0.2);
}

.wifi-menu .wifi-item .connect:pressed {
    background-color: rgba(255, 255, 255, 0.3);
}

.wifi-menu .footer {
    font-size: 12px;
    font-weight: 600;
    padding: 12px;
    margin-top: 2px;
    color: #9399b2;
    background-color: rgba(17, 17, 27, 0.6);
    border-top: 1px solid rgba(255, 255, 255, 0.1);
}

.wifi-menu .footer .settings-button {
    background-color: transparent;
    border: none;
    padding: 0 2px;
    min-width: 26px;
    min-height: 26px;
    color: #fff;
}

.wifi-menu .footer .refresh-icon {
    font-family: 'Segoe Fluent Icons';
    background-color: transparent;
    border: none;
    min-width: 26px;
    min-height: 26px;
    color: #fff;
}

.wifi-menu .footer .refresh-icon:hover {
    background-color: rgba(255, 255, 255, 0.1);
    border-radius: 4px;
}

.clock-widget {
    padding: 0 4px 0 0px;
}
.clock-widget .icon {
    color: #89dceb;
    font-size: 14px;
    padding-right: 4px;
}
.clock-widget .icon.alarm {
    color: #f38ba8;
    margin-left: 4px;
}

.clock-widget .label.alarm {
    color: rgba(255, 255, 255, 0.2);
    margin-left: 4px;
}


.clock-popup.alarm,
.clock-popup.timer,
.clock-popup.calendar {
    min-width: 460px;
    background-color: var(--microfiberhalf);
}

.clock-popup.calendar .calendar-table,
.clock-popup.calendar .calendar-table::item {
    background-color: rgba(17, 17, 27, 0);
    color: var(--glacier);
    margin: 0;
    padding: 0;
    border: none;
    outline: none;
    
}
.clock-popup.calendar .calendar-table::item:selected {
    color: #282936;
    font-weight: bold;
    background-color: rgba(255, 255, 255, 0.2);
    border-radius: 12px;
}
.clock-popup.calendar .day-label {
    margin-top: 20px;
}
.clock-popup.calendar .day-label,
.clock-popup.calendar .month-label,
.clock-popup.calendar .date-label {
    font-size: 16px;
    color: #fff;
    font-weight: 700;
    min-width: 180px;
    max-width: 180px;
}
.clock-popup.calendar .month-label {
    font-weight: normal;
}
.clock-popup.calendar .date-label {
    font-size: 88px;
    font-weight: 900;
    color: rgb(255, 255, 255);
    margin-top: -20px;
}
.clock-popup.calendar .extended-container {
    border-left: 1px solid rgba(255, 255, 255, 0.2);
    background-color: transparent;
    padding-left: 16px;
}
.clock-popup.calendar .extended-container .button.alarm.small,
.clock-popup.calendar .extended-container .button.timer.small {
    min-width: 32px;
    min-height: 16px;
    font-size: 12px;
    padding: 4px 8px;
    border-radius: 2px;
}
.clock-popup.calendar .extended-container .upcoming-events-header {
    font-size: 12px;
    font-weight: 600;
    margin: 4px 0 8px 0;
    color: #d2d6e2;
}
.clock-popup.calendar .extended-container .upcoming-events-item {
    font-size: 12px;
    font-weight: 600;
    padding: 3px 0;
    color: #b2b6c0;
}
.clock-popup.calendar .extended-container .upcoming-events-item:hover {
    color: #ced1d8;
}

/* Alarm and Timer Dialog Containers */
.clock-popup.timer .clock-popup-container,
.clock-popup.alarm .clock-popup-container {
    padding: 16px;
}
.clock-popup.timer .clock-popup-footer,
.clock-popup.alarm .clock-popup-footer {
    padding: 16px;
    border-top: 1px solid rgb(0, 0, 0);
    background-color: rgba(0, 0, 0, 0.3);
}
.clock-popup .clock-label-timer {
    font-size: 13px;
    font-weight: 600;
    color: #8d9196;
}
.clock-popup .clock-input-time {
    font-size: 48px;
    background-color: transparent;
    border: none;
    font-weight: 600;
    color: #ced3d8;
}
.clock-popup .clock-input-time.colon {
    padding-bottom: 8px;
}

/* Dialog Buttons */
.clock-popup .button {
    border-radius: 4px;
    font-weight: 600;
    font-size: 13px;
    min-height: 28px;
    min-width: 64px;
    margin: 4px 0;
    background-color: rgba(255, 255, 255, 0.1);
}
.clock-popup .button.save,
.clock-popup .button.start,
.clock-popup .button.delete,
.clock-popup .button.cancel {
    min-width: 120px;
}

.clock-popup .button.save,
.clock-popup .button.start {
    background-color: rgba(0, 110, 255, 0.5);
    margin-right: 8px;
}

.clock-popup .button.save:hover,
.clock-popup .button.start:hover {
    background-color: rgba(0, 110, 255, 0.7);
}
.clock-popup .button.delete {
    background-color: rgba(255, 80, 80, 0.5);
}
.clock-popup .button.delete:hover {
    background-color: rgba(255, 80, 80, 0.7);
}
.clock-popup .button.is-alarm-enabled {
    background-color: rgba(0, 110, 255, 0.5);
}
.clock-popup .button.is-alarm-enabled:hover {
    background-color: rgba(0, 110, 255, 0.7);
}
.clock-popup .button.is-alarm-disabled {
    background-color: rgba(255, 255, 255, 0.2);
}
.clock-popup .button.day {
    background-color: rgba(255, 255, 255, 0.1);
    max-height: 20px;
    min-height: 20px;
}
.clock-popup .button.day:checked {
    background-color: rgba(0, 110, 255, 0.5);
}
.clock-popup .button.quick-option {
    background-color: rgba(255, 255, 255, 0.1);
}
.clock-popup .button.quick-option:checked {
    background-color: rgba(0, 110, 255, 0.5);
}
.clock-popup .button:hover {
    background-color: rgba(255, 255, 255, 0.2);
}
.clock-popup .button:disabled {
    background-color: rgba(100, 100, 100, 0.2);
    color: rgba(150, 150, 150, 0.7);
}
.clock-popup .alarm-input-title {
    font-size: 14px;
    font-weight: 600;
    color: #d2d6e2;
    background-color: rgba(255, 255, 255, 0.1);
    border: 1px solid transparent;
    border-radius: 4px;
    padding: 4px 8px;
    margin-top: 8px;
    outline: none;
    min-width: 300px;
}

.clock-popup .alarm-input-title:focus {
    border: 1px solid #0078D4;
}

/* Active Alarm Popup Window */
.active-alarm-window {
    background-color: rgba(255, 255, 255, 0.048);
    max-width: 500px;
    min-width: 500px;
    padding: 32px;
}
.active-alarm-window .alarm-title-icon {
    font-size: 64px;
    color: #ffffff;
    margin-bottom: 16px;
}
.active-alarm-window .alarm-title {
    font-size: 24px;
    font-weight: 600;
    color: #ffffff;
    max-width: 500px;
    min-width: 500px;
}
.active-alarm-window .alarm-info {
    font-size: 16px;
    font-weight: 600;
    color: #b2b6c0;
    margin-bottom: 32px;
}
.active-alarm-window .button {
    border-radius: 4px;
    font-weight: 600;
    font-size: 14px;
    min-height: 36px;
    min-width: 100px;
    margin: 0 4px;
    background-color: rgba(255, 255, 255, 0.1);
}
.active-alarm-window .button:hover {
    background-color: rgba(255, 255, 255, 0.3);
}
